### ISSUE TITLE
Add support for profiling AJAX requests

### ISSUE THREAD

**Issue by timbonicus** [tomdcc/grails-miniprofiler#7]
The miniprofiler's namesake supports AJAX request timings. With dynamic apps, this can be a non-trivial amount of requests that could use the miniprofiler to help with performance tuning.

**Comment by tomdcc** [comment]
Hi Tim!

I would definitely like this working for AJAX requests. I know the javascript that I grabbed from "upstream" supports AJAX requests, but I haven't had time to look at what it might take to get it working.

Honestly, the code here it in a pretty bad state, I grabbed as much from the .net miniprofiler and hacked at it until it worked, under a very tight deadline before GGX last year. I would really like to tidy it up, maybe grab the latest JS from upstream, and then really attack AJAX requests. The problem is time - I really can't promise when I'll get to AJAX requests, just that it is pretty close to the top of my TODO list.

Contributions very welcome! :)

**Comment by tomdcc** [comment]
Hi again Tim

It turns out that I had the opportunity to have a look at this today, and I managed to get it working on my AngularJS app. I believe that the miniprofiler JS code from "upstream" has support for jQuery and extjs AJAX calls as well.

Could you try out with the profiler 0.2-SNAPSHOT version and let me know if it works for you? If it doesn't, could you let me know which JS framework you are using to do the AJAX?

Cheers

Tom

**Comment by timbonicus** [comment]
Wow, fast turnaround Tom! That is awesome. The 0.2-SNAPSHOT version is working great with jQuery AJAX calls. This will be immensely helpful. Thanks for taking the time to look into it!

**Comment by tomdcc** [comment]
Just FYI I've released version 0.2 with this fix.

**Comment by MichaelMorett** [comment]
Don't forget to update the install docs.
